export interface ThemeColors {
  background: string
  foreground: string
  card: string
  cardForeground: string
  popover: string
  popoverForeground: string
  primary: string
  primaryForeground: string
  secondary: string
  secondaryForeground: string
  muted: string
  mutedForeground: string
  accent: string
  accentForeground: string
  destructive: string
  destructiveForeground: string
  border: string
  input: string
  ring: string
  sidebar: string
  sidebarForeground: string
  sidebarPrimary: string
  sidebarPrimaryForeground: string
  sidebarAccent: string
  sidebarAccentForeground: string
  sidebarBorder: string
  sidebarRing: string
}

export interface ThemeDefinition {
  id: string
  nome: string
  descricao: string
  previewColors: [string, string, string]
  cores: ThemeColors
  backgroundImage?: string
  backgroundOpacity?: number
  backgroundSize?: string
  backgroundRepeat?: string
  backgroundMask?: string
  scrollbarTrack?: string
  scrollbarThumb?: string
  scrollbarThumbHover?: string
}

const TEMA_PADRAO: ThemeDefinition = {
  id: 'padrao',
  nome: 'Padrão',
  descricao: 'Tema escuro clássico[cite: 7]',
  previewColors: ['#000000', '#111111', '#ffffff'],
  cores: {
    background: '#000000',
    foreground: '#e5e5e5',
    card: '#0a0a0a',
    cardForeground: '#e5e5e5',
    popover: '#0a0a0a',
    popoverForeground: '#e5e5e5',
    primary: '#ffffff',
    primaryForeground: '#000000',
    secondary: '#111111',
    secondaryForeground: '#e5e5e5',
    muted: '#171717',
    mutedForeground: '#737373',
    accent: '#ffffff',
    accentForeground: '#000000',
    destructive: '#ff4444',
    destructiveForeground: '#ffffff',
    border: '#1a1a1a',
    input: '#1a1a1a',
    ring: '#ffffff',
    sidebar: '#050505',
    sidebarForeground: '#e5e5e5',
    sidebarPrimary: '#ffffff',
    sidebarPrimaryForeground: '#000000',
    sidebarAccent: '#111111',
    sidebarAccentForeground: '#e5e5e5',
    sidebarBorder: '#1a1a1a',
    sidebarRing: '#ffffff',
  },
}

const TEMA_SELOCO: ThemeDefinition = {
  id: 'seloco',
  nome: 'Seloco',
  descricao: 'Tema rosinha escuro misterioso e elegante',
  previewColors: ['#12080d', '#db2777', '#f472b6'],
  cores: {
    background: '#0c0509',
    foreground: '#fce7f3',
    card: '#14080f',
    cardForeground: '#fce7f3',
    popover: '#14080f',
    popoverForeground: '#fce7f3',
    primary: '#db2777',
    primaryForeground: '#ffffff',
    secondary: '#200d18',
    secondaryForeground: '#fce7f3',
    muted: '#1b0a14',
    mutedForeground: '#a16287',
    accent: '#ec4899',
    accentForeground: '#ffffff',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#331226',
    input: '#331226',
    ring: '#db2777',
    sidebar: '#0f060b',
    sidebarForeground: '#fce7f3',
    sidebarPrimary: '#db2777',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#200d18',
    sidebarAccentForeground: '#fce7f3',
    sidebarBorder: '#331226',
    sidebarRing: '#db2777',
  },
  backgroundImage: '/themes/seloco.jpg',
  backgroundOpacity: 0.18,
  backgroundSize: 'cover',
  backgroundRepeat: 'no-repeat',
  backgroundMask: 'radial-gradient(ellipse 80% 80% at 50% 50%, black 30%, transparent 90%)',
  scrollbarTrack: '#14080f',
  scrollbarThumb: '#331226',
  scrollbarThumbHover: '#592043',
}

const TEMA_HOLY: ThemeDefinition = {
  id: 'holy',
  nome: 'Holy',
  descricao: 'Tema cinza elegante com tons sofisticados e atmosfera neutra[cite: 7]',
  previewColors: ['#121212', '#71717a', '#e4e4e7'],
  cores: {
    background: '#0f0f11',
    foreground: '#f4f4f5',
    card: '#18181b',
    cardForeground: '#f4f4f5',
    popover: '#18181b',
    popoverForeground: '#f4f4f5',
    primary: '#e4e4e7',
    primaryForeground: '#09090b',
    secondary: '#27272a',
    secondaryForeground: '#f4f4f5',
    muted: '#1f1f23',
    mutedForeground: '#a1a1aa',
    accent: '#a1a1aa',
    accentForeground: '#09090b',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#27272a',
    input: '#27272a',
    ring: '#71717a',
    sidebar: '#121215',
    sidebarForeground: '#f4f4f5',
    sidebarPrimary: '#e4e4e7',
    sidebarPrimaryForeground: '#09090b',
    sidebarAccent: '#27272a',
    sidebarAccentForeground: '#f4f4f5',
    sidebarBorder: '#27272a',
    sidebarRing: '#71717a',
  },
  backgroundImage: '/themes/holy.jpg',
  backgroundOpacity: 0.16,
  backgroundSize: 'cover',
  backgroundRepeat: 'no-repeat',
  backgroundMask: 'radial-gradient(ellipse 80% 80% at 50% 50%, black 30%, transparent 90%)',
  scrollbarTrack: '#18181b',
  scrollbarThumb: '#27272a',
  scrollbarThumbHover: '#3f3f46',
}

const TEMA_BONITA: ThemeDefinition = {
  id: 'bonita',
  nome: 'Bonita',
  descricao: 'Estilo luxuoso inspirado em mansão, carros de luxo e tons dourados/terrosos[cite: 7]',
  previewColors: ['#0c0a09', '#d97706', '#292524'],
  cores: {
    background: '#0a0908',
    foreground: '#f5f2eb',
    card: '#141210',
    cardForeground: '#f5f2eb',
    popover: '#141210',
    popoverForeground: '#f5f2eb',
    primary: '#d97706',
    primaryForeground: '#0a0a0a',
    secondary: '#1c1917',
    secondaryForeground: '#f5f2eb',
    muted: '#181513',
    mutedForeground: '#a89f91',
    accent: '#f59e0b',
    accentForeground: '#0a0a0a',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#292524',
    input: '#292524',
    ring: '#d97706',
    sidebar: '#0d0b0a',
    sidebarForeground: '#f5f2eb',
    sidebarPrimary: '#d97706',
    sidebarPrimaryForeground: '#0a0a0a',
    sidebarAccent: '#1c1917',
    sidebarAccentForeground: '#f5f2eb',
    sidebarBorder: '#292524',
    sidebarRing: '#d97706',
  },
  backgroundImage: '/themes/bonita.jpg',
  backgroundOpacity: 0.18,
  backgroundSize: 'cover',
  backgroundRepeat: 'no-repeat',
  backgroundMask: 'radial-gradient(ellipse 80% 80% at 50% 50%, black 30%, transparent 90%)',
  scrollbarTrack: '#141210',
  scrollbarThumb: '#292524',
  scrollbarThumbHover: '#443c38',
}

const TEMA_HELLO_KITTY: ThemeDefinition = {
  id: 'hello-kitty',
  nome: 'Hello Kitty',
  descricao: 'Rosa fofo com decorações da Hello Kitty[cite: 7]',
  previewColors: ['#1a0a10', '#ff6b9d', '#ffb3d1'],
  cores: {
    background: '#0d0608',
    foreground: '#f5e6ec',
    card: '#150a0f',
    cardForeground: '#f5e6ec',
    popover: '#150a0f',
    popoverForeground: '#f5e6ec',
    primary: '#ff6b9d',
    primaryForeground: '#1a0a10',
    secondary: '#1f0e15',
    secondaryForeground: '#f5e6ec',
    muted: '#1a0c12',
    mutedForeground: '#b87a94',
    accent: '#ff6b9d',
    accentForeground: '#1a0a10',
    destructive: '#ff4466',
    destructiveForeground: '#ffffff',
    border: '#2a1520',
    input: '#2a1520',
    ring: '#ff6b9d',
    sidebar: '#0a0507',
    sidebarForeground: '#f5e6ec',
    sidebarPrimary: '#ff6b9d',
    sidebarPrimaryForeground: '#1a0a10',
    sidebarAccent: '#1f0e15',
    sidebarAccentForeground: '#f5e6ec',
    sidebarBorder: '#2a1520',
    sidebarRing: '#ff6b9d',
  },
  backgroundImage: '/themes/hellokittybg.jpg',
  backgroundOpacity: 0.18,
  backgroundSize: 'cover',
  backgroundRepeat: 'no-repeat',
  backgroundMask: 'radial-gradient(ellipse 80% 80% at 50% 50%, black 30%, transparent 90%)',
  scrollbarTrack: '#150a0f',
  scrollbarThumb: '#2a1520',
  scrollbarThumbHover: '#3d1f30',
}

const TEMA_CYBERPUNK: ThemeDefinition = {
  id: 'cyberpunk',
  nome: 'Cyberpunk',
  descricao: 'Neon com visual futurista[cite: 7]',
  previewColors: ['#0a0a14', '#00ffcc', '#ff0066'],
  cores: {
    background: '#05050d',
    foreground: '#e0f0ef',
    card: '#0a0a16',
    cardForeground: '#e0f0ef',
    popover: '#0a0a16',
    popoverForeground: '#e0f0ef',
    primary: '#00ffcc',
    primaryForeground: '#050d0b',
    secondary: '#0f0f1e',
    secondaryForeground: '#e0f0ef',
    muted: '#12122a',
    mutedForeground: '#6b8a85',
    accent: '#00ffcc',
    accentForeground: '#050d0b',
    destructive: '#ff0066',
    destructiveForeground: '#ffffff',
    border: '#1a1a35',
    input: '#1a1a35',
    ring: '#00ffcc',
    sidebar: '#040410',
    sidebarForeground: '#e0f0ef',
    sidebarPrimary: '#00ffcc',
    sidebarPrimaryForeground: '#050d0b',
    sidebarAccent: '#0f0f1e',
    sidebarAccentForeground: '#e0f0ef',
    sidebarBorder: '#1a1a35',
    sidebarRing: '#00ffcc',
  },
  scrollbarTrack: '#0a0a16',
  scrollbarThumb: '#1a1a35',
  scrollbarThumbHover: '#2a2a4a',
}

const TEMA_DRACULA: ThemeDefinition = {
  id: 'dracula',
  nome: 'Dracula',
  descricao: 'Tema escuro roxo clássico[cite: 7]',
  previewColors: ['#282a36', '#bd93f9', '#ff79c6'],
  cores: {
    background: '#1a1b26',
    foreground: '#f8f8f2',
    card: '#21222e',
    cardForeground: '#f8f8f2',
    popover: '#21222e',
    popoverForeground: '#f8f8f2',
    primary: '#bd93f9',
    primaryForeground: '#1a1b26',
    secondary: '#282a36',
    secondaryForeground: '#f8f8f2',
    muted: '#2a2c3a',
    mutedForeground: '#6272a4',
    accent: '#bd93f9',
    accentForeground: '#1a1b26',
    destructive: '#ff5555',
    destructiveForeground: '#f8f8f2',
    border: '#343746',
    input: '#343746',
    ring: '#bd93f9',
    sidebar: '#171822',
    sidebarForeground: '#f8f8f2',
    sidebarPrimary: '#bd93f9',
    sidebarPrimaryForeground: '#1a1b26',
    sidebarAccent: '#282a36',
    sidebarAccentForeground: '#f8f8f2',
    sidebarBorder: '#343746',
    sidebarRing: '#bd93f9',
  },
  scrollbarTrack: '#21222e',
  scrollbarThumb: '#343746',
  scrollbarThumbHover: '#44475a',
}

const TEMA_KUROMI: ThemeDefinition = {
  id: 'kuromi',
  nome: 'Kuromi',
  descricao: 'Roxo escuro com estilo punk fofo[cite: 7]',
  previewColors: ['#110b18', '#9b59b6', '#c084fc'],
  cores: {
    background: '#0a0710',
    foreground: '#ede6f5',
    card: '#110b18',
    cardForeground: '#ede6f5',
    popover: '#110b18',
    popoverForeground: '#ede6f5',
    primary: '#b476d4',
    primaryForeground: '#0e0816',
    secondary: '#170e22',
    secondaryForeground: '#ede6f5',
    muted: '#1a1025',
    mutedForeground: '#9680aa',
    accent: '#b476d4',
    accentForeground: '#0e0816',
    destructive: '#ff4477',
    destructiveForeground: '#ffffff',
    border: '#261838',
    input: '#261838',
    ring: '#b476d4',
    sidebar: '#080510',
    sidebarForeground: '#ede6f5',
    sidebarPrimary: '#b476d4',
    sidebarPrimaryForeground: '#0e0816',
    sidebarAccent: '#170e22',
    sidebarAccentForeground: '#ede6f5',
    sidebarBorder: '#261838',
    sidebarRing: '#b476d4',
  },
  backgroundImage: '/themes/kuromi.jpg',
  backgroundOpacity: 0.15,
  backgroundSize: 'cover',
  backgroundRepeat: 'no-repeat',
  backgroundMask: 'radial-gradient(ellipse 80% 80% at 50% 50%, black 30%, transparent 90%)',
  scrollbarTrack: '#110b18',
  scrollbarThumb: '#261838',
  scrollbarThumbHover: '#3a2550',
}

const TEMA_VAMPIRO: ThemeDefinition = {
  id: 'vampiro',
  nome: 'Vampiro',
  descricao: 'Vermelho sangue e preto gótico com atmosfera sombria[cite: 7]',
  previewColors: ['#0d0404', '#dc2626', '#f87171'],
  cores: {
    background: '#070202',
    foreground: '#f3e8e8',
    card: '#120505',
    cardForeground: '#f3e8e8',
    popover: '#120505',
    popoverForeground: '#f3e8e8',
    primary: '#dc2626',
    primaryForeground: '#ffffff',
    secondary: '#1f0808',
    secondaryForeground: '#f3e8e8',
    muted: '#190606',
    mutedForeground: '#996666',
    accent: '#ef4444',
    accentForeground: '#ffffff',
    destructive: '#b91c1c',
    destructiveForeground: '#ffffff',
    border: '#320d0d',
    input: '#320d0d',
    ring: '#dc2626',
    sidebar: '#050101',
    sidebarForeground: '#f3e8e8',
    sidebarPrimary: '#dc2626',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#1f0808',
    sidebarAccentForeground: '#f3e8e8',
    sidebarBorder: '#320d0d',
    sidebarRing: '#dc2626',
  },
  backgroundImage: '/themes/vampiro.jpg',
  backgroundOpacity: 0.16,
  backgroundSize: 'cover',
  backgroundRepeat: 'no-repeat',
  backgroundMask: 'radial-gradient(ellipse 80% 80% at 50% 50%, black 30%, transparent 90%)',
  scrollbarTrack: '#120505',
  scrollbarThumb: '#320d0d',
  scrollbarThumbHover: '#521414',
}

const TEMA_MANGA: ThemeDefinition = {
  id: 'manga',
  nome: 'Manga',
  descricao: 'Papel branco com tinta preta, painéis recortados e impacto[cite: 7]',
  previewColors: ['#f5f1e8', '#000000', '#c91919'],
  cores: {
    background: '#f5f1e8',
    foreground: '#0a0a0a',
    card: '#ffffff',
    cardForeground: '#0a0a0a',
    popover: '#ffffff',
    popoverForeground: '#0a0a0a',
    primary: '#000000',
    primaryForeground: '#ffffff',
    secondary: '#ece5d3',
    secondaryForeground: '#0a0a0a',
    muted: '#eae3d0',
    mutedForeground: '#4a4a4a',
    accent: '#000000',
    accentForeground: '#ffffff',
    destructive: '#c91919',
    destructiveForeground: '#ffffff',
    border: '#0a0a0a',
    input: '#0a0a0a',
    ring: '#000000',
    sidebar: '#ebe3cf',
    sidebarForeground: '#0a0a0a',
    sidebarPrimary: '#000000',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#ded4bb',
    sidebarAccentForeground: '#0a0a0a',
    sidebarBorder: '#0a0a0a',
    sidebarRing: '#000000',
  },
  backgroundImage: '/themes/manga-pattern.svg',
  backgroundOpacity: 0.08,
  backgroundSize: '300px',
  backgroundRepeat: 'repeat',
  backgroundMask: 'radial-gradient(ellipse 95% 95% at 50% 50%, black 30%, transparent 100%)',
  scrollbarTrack: '#ece5d3',
  scrollbarThumb: '#0a0a0a',
  scrollbarThumbHover: '#333333',
}

const TEMA_NEO_BRUTALISM: ThemeDefinition = {
  id: 'neo-brutalism',
  nome: 'Neo-Brutalism Soft',
  descricao: 'Pastel cremoso com bordas grossas e sombras sólidas[cite: 7]',
  previewColors: ['#fff4e6', '#ff8fa3', '#1a1a1a'],
  cores: {
    background: '#fff4e6',
    foreground: '#1a1a1a',
    card: '#ffffff',
    cardForeground: '#1a1a1a',
    popover: '#ffffff',
    popoverForeground: '#1a1a1a',
    primary: '#ff8fa3',
    primaryForeground: '#1a1a1a',
    secondary: '#ffe5c2',
    secondaryForeground: '#1a1a1a',
    muted: '#f5e6d3',
    mutedForeground: '#6b6b6b',
    accent: '#ff8fa3',
    accentForeground: '#1a1a1a',
    destructive: '#ff4d4d',
    destructiveForeground: '#ffffff',
    border: '#1a1a1a',
    input: '#1a1a1a',
    ring: '#ff8fa3',
    sidebar: '#ffe5c2',
    sidebarForeground: '#1a1a1a',
    sidebarPrimary: '#ff8fa3',
    sidebarPrimaryForeground: '#1a1a1a',
    sidebarAccent: '#fff0da',
    sidebarAccentForeground: '#1a1a1a',
    sidebarBorder: '#1a1a1a',
    sidebarRing: '#ff8fa3',
  },
  backgroundImage: '/themes/neobrutalism-pattern.svg',
  backgroundOpacity: 0.06,
  backgroundSize: '120px',
  backgroundRepeat: 'repeat',
  backgroundMask: 'radial-gradient(ellipse 90% 90% at 50% 50%, black 40%, transparent 100%)',
  scrollbarTrack: '#ffe5c2',
  scrollbarThumb: '#1a1a1a',
  scrollbarThumbHover: '#3a3a3a',
}

const TEMA_QUADRILHA: ThemeDefinition = {
  id: 'quadrilha',
  nome: 'Quadrilha',
  descricao: 'Estilo urbano sombrio com jaqueta de couro, tons escuros e detalhes dourados/metálicos[cite: 7]',
  previewColors: ['#0a090b', '#d4af37', '#1c1a1f'],
  cores: {
    background: '#09080a',
    foreground: '#f1ede9',
    card: '#131115',
    cardForeground: '#f1ede9',
    popover: '#131115',
    popoverForeground: '#f1ede9',
    primary: '#d4af37',
    primaryForeground: '#09080a',
    secondary: '#1c1920',
    secondaryForeground: '#f1ede9',
    muted: '#17141a',
    mutedForeground: '#8c828e',
    accent: '#e6c552',
    accentForeground: '#09080a',
    destructive: '#e63946',
    destructiveForeground: '#ffffff',
    border: '#2a2530',
    input: '#2a2530',
    ring: '#d4af37',
    sidebar: '#0d0b0f',
    sidebarForeground: '#f1ede9',
    sidebarPrimary: '#d4af37',
    sidebarPrimaryForeground: '#09080a',
    sidebarAccent: '#1c1920',
    sidebarAccentForeground: '#f1ede9',
    sidebarBorder: '#2a2530',
    sidebarRing: '#d4af37',
  },
  backgroundImage: '/themes/quadrilha.jpg',
  backgroundOpacity: 0.18,
  backgroundSize: 'cover',
  backgroundRepeat: 'no-repeat',
  backgroundMask: 'radial-gradient(ellipse 80% 80% at 50% 50%, black 30%, transparent 90%)',
  scrollbarTrack: '#131115',
  scrollbarThumb: '#2a2530',
  scrollbarThumbHover: '#3d3545',
}

const TEMA_DANG: ThemeDefinition = {
  id: 'dang',
  nome: 'Dang',
  descricao: 'Tema cinza moderno com efeito de glow escuro e atmosfera imersiva',
  previewColors: ['#0d0d0f', '#6b7280', '#9ca3af'],
  cores: {
    background: '#08080a',
    foreground: '#f3f4f6',
    card: '#101014',
    cardForeground: '#f3f4f6',
    popover: '#101014',
    popoverForeground: '#f3f4f6',
    primary: '#9ca3af',
    primaryForeground: '#08080a',
    secondary: '#18181c',
    secondaryForeground: '#f3f4f6',
    muted: '#141418',
    mutedForeground: '#9ca3af',
    accent: '#d1d5db',
    accentForeground: '#08080a',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#27272a',
    input: '#27272a',
    ring: '#6b7280',
    sidebar: '#0b0b0e',
    sidebarForeground: '#f3f4f6',
    sidebarPrimary: '#9ca3af',
    sidebarPrimaryForeground: '#08080a',
    sidebarAccent: '#18181c',
    sidebarAccentForeground: '#f3f4f6',
    sidebarBorder: '#27272a',
    sidebarRing: '#6b7280',
  },
  backgroundImage: '/themes/dang.jpg',
  backgroundOpacity: 0.18,
  backgroundSize: 'cover',
  backgroundRepeat: 'no-repeat',
  backgroundMask: 'radial-gradient(ellipse 80% 80% at 50% 50%, black 30%, transparent 90%)',
  scrollbarTrack: '#101014',
  scrollbarThumb: '#27272a',
  scrollbarThumbHover: '#3f3f46',
}

export const TEMAS: ThemeDefinition[] = [
  TEMA_PADRAO,
  TEMA_SELOCO,
  TEMA_HOLY,
  TEMA_BONITA,
  TEMA_QUADRILHA,
  TEMA_HELLO_KITTY,
  TEMA_KUROMI,
  TEMA_VAMPIRO,
  TEMA_MANGA,
  TEMA_NEO_BRUTALISM,
  TEMA_CYBERPUNK,
  TEMA_DRACULA,
  TEMA_DANG,
]

export function getTema(id: string): ThemeDefinition | undefined {
  return TEMAS.find((t) => t.id === id)
}